# Generated by Django 4.0.3 on 2022-08-28 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0002_habitacion_imagen_habitacion'),
        ('servicios', '0005_alter_horarios_options_alter_servicios_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('hora_ingreso', models.CharField(max_length=10, verbose_name='Hora de ingreso')),
                ('hora_salida', models.CharField(max_length=10, verbose_name='Hora de salida')),
                ('numero_personas', models.IntegerField(verbose_name='Número de Personas')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo de Cliente')),
                ('numero_contacto', models.CharField(max_length=12, verbose_name='Numero de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
