# Generated by Django 4.0.3 on 2022-08-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosReserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('nombre_servicio', models.CharField(max_length=100, verbose_name='Nombre de Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('capacidad', models.CharField(default='', max_length=50, verbose_name='Capacidad')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_servicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_servicio',
            field=models.ManyToManyField(to='Reserva.serviciosreserva'),
        ),
    ]
