# Generated by Django 4.0.3 on 2022-09-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0002_serviciosreserva_remove_reserva_id_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='direccion',
            field=models.CharField(default='', max_length=40, verbose_name='Direccion de Cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='documento_identidad',
            field=models.CharField(default='', max_length=12, verbose_name='Documento de Identidad'),
        ),
    ]
