# Generated by Django 4.0.3 on 2022-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0003_reserva_direccion_reserva_documento_identidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total_gasto',
            field=models.FloatField(default=0, verbose_name='Costo de habitacion'),
        ),
    ]
